--------------------------------
-- COM05 - Suivi Réversibilité
--------------------------------

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

select loa.t_orno as OrdreAchat
,loa.t_odat as DateOrdre
,ligliee.t_srvo as OrdreServiceLie
,presta.t_acln as LignePrestation
,presta.t_sern as Chassis
,(case left(presta.t_sern, 3)
when 'JMB' then 'Mitsubishi'
when 'JA' then 'Isuzu'
when 'JF' then 'Fuji Heavy Industries (Subaru)'
when 'JH' then 'Honda'
when 'JK' then 'Kawasaki (motocycles)'
when 'JM' then 'Mazda'
when 'JN' then 'Nissan'
when 'JS' then 'Suzuki'
when 'JT' then 'Toyota'
when 'KL' then 'Daewoo General Motors Corée du Sud'
when 'KM8' then 'Hyundai'
when 'KMH' then 'Hyundai'
when 'KNA' then 'Kia'
when 'KNB' then 'Kia'
when 'KNC' then 'Kia'
when 'KNM' then 'Renault Samsung'
when 'L56' then 'Renault Samsung'
when 'L5Y' then 'MERATO MOTORCYCLE Taizhou Zhongneng'
when 'LDY' then 'Zhongtong Coach, Chine'
when 'LKL' then 'Suzhou King Long, Chine'
when 'LSY' then 'Brilliance Zhonghua'
when 'LTV' then 'Toyota Tian Jin'
when 'LVS' then 'Ford Chang An'
when 'LZM' then 'MAN Chine'
when 'LZE' then 'Isuzu Guangzhou, Chine'
when 'LZG' then 'Shaanxi Automobile Group, Chine'
when 'LZY' then 'Yutong Zhengzhou, Chine'
when 'MA3' then 'Suzuki Inde'
when 'NLE' then 'Mercedes-Benz Camions Turquie'
when 'NM4' then 'Fiat-Tofaş Turquie'
when 'NMT' then 'Toyota Turquie'
when 'S2D' then 'Chrysler (Simca) France'
when 'SAL' then 'Land Rover'
when 'SAJ' then 'Jaguar'
when 'SAR' then 'Rover'
when 'SB1' then 'Toyota UK'
when 'SCC' then 'Lotus Cars'
when 'SCE' then 'DeLorean Motor Cars N. Ireland (UK)'
when 'SDB' then 'Peugeot UK'
when 'SFD' then 'Alexander Dennis UK'
when 'SHS' then 'Honda UK'
when 'SJN' then 'Nissan UK'
when 'TMB' then 'Škoda Auto'
when 'TMT' then 'Tatra'
when 'TRA' then 'Irisbus Ikarus Bus'
when 'TRU' then 'Audi Hongrie'
when 'TSM' then 'Suzuki Hongrie'
when 'UU1' then 'Renault Dacia Roumanie'
when 'VF1' then 'Renault France'
when 'VF3' then 'Peugeot France'
when 'VF4' then 'Talbot France'
when 'VF6' then 'Renault Trucks (Volvo) France'
when 'VF7' then 'Citroën France'
when 'VF8' then 'Matra'
when 'VF9' then 'Bugatti'
when 'VFA' then 'Alpine Renault'
when 'VJ1' then 'Heuliez Bus'
when 'VJ2' then 'Mia Electric'
when 'VN1' then 'Opel (Utilitaires) France'
when 'VNV' then 'Nissan (Utilitaires) France'
when 'VNK' then 'Toyota France'
when 'VR1' then 'DS Automobiles France'
when 'VR3' then 'Peugeot France'
when 'VR7' then 'Citroën France'
when 'VSS' then 'SEAT Espagne'
when 'VSX' then 'Opel Espagne'
when 'VS6' then 'Ford Espagne'
when 'VSG' then 'Nissan Espagne'
when 'VSE' then 'Santana Motors'
when 'VWV' then 'Volkswagen Espagne'
when 'WAU' then 'Audi'
when 'WUA' then 'Quattro GmbH (de) (Modèles sportifs Audi (Gamme RS))'
when 'WBA' then 'BMW'
when 'WBS' then 'BMW M'
when 'WDB' then 'Mercedes-Benz'
when 'WDC' then 'DaimlerChrysler (annulé en 2006)'
when 'WDD' then 'McLaren'
when 'WF0' then 'Ford Allemagne'
when 'WMA' then 'MAN'
when 'WMW' then 'MINI'
when 'WP0' then 'Porsche'
when 'WP1' then 'Porsche'
when 'W0L' then 'Opel'
when 'W0V' then 'Opel'
when 'WVW' then 'Volkswagen'
when 'WV1' then 'Volkswagen LCV'
when 'WV2' then 'Volkswagen Bus/Van'
when 'XL9' then 'Spyker'
when 'XLR' then 'DAF Trucks NV Netherland'
when 'XTA' then 'Lada/AutoVaz Russie'
when 'YK1' then 'Saab'
when 'YS2' then 'Scania AB'
when 'YS3' then 'Saab'
when 'YV1' then 'Volvo Automobiles (Ford)'
when 'YV4' then 'Volvo Automobiles'
when 'YV2' then 'Volvo Camions'
when 'YV3' then 'Volvo Bus'
when 'ZAM' then 'Maserati'
when 'ZAP' then 'Piaggio/Vespa/Gilera'
when 'ZAR' then 'Alfa Romeo'
when 'ZCF' then 'Iveco'
when 'ZCG' then 'Cagiva SpA'
when 'ZDM' then 'Ducati Motor Holdings SpA'
when 'ZDF' then 'Ferrari Dino'
when 'ZD4' then 'Aprilia'
when 'ZFA' then 'Fiat Italie'
when 'ZFC' then 'Fiat V.I. Italie'
when 'ZFF' then 'Ferrari'
when 'ZHW' then 'Lamborghini'
when 'ZLA' then 'Lancia Italie'
when 'ZOM' then 'OM Camions'
when '1C3' then 'Chrysler USA'
when '1D3' then 'Dodge USA'
when '1FA' then 'Ford Motor Company USA'
when '1FB' then 'Ford Motor Company USA'
when '1FC' then 'Ford Motor Company USA'
when '1FD' then 'Ford Motor Company USA'
when '1FM' then 'Ford Motor Company USA'
when '1FT' then 'Ford Motor Company USA'
when '1FU' then 'Freightliner'
when '1FV' then 'Freightliner'
when '1F9' then 'FWD Corp.'
when '1G' then 'General Motors USA'
when '1GC' then 'Chevrolet Camions USA'
when '1GT' then 'GMC Camions USA'
when '1G1' then 'Chevrolet USA'
when '1G2' then 'Pontiac USA'
when '1G3' then 'Oldsmobile USA'
when '1G4' then 'Buick USA'
when '1G6' then 'Cadillac USA'
when '1GM' then 'Pontiac USA'
when '1G8' then 'Saturn USA'
when '1H' then 'Honda USA'
when '1HD' then 'Harley-Davidson'
when '1J4' then 'Jeep'
when '1L' then 'Lincoln USA'
when '1ME' then 'Mercury USA'
when '1M1' then 'Mack Truck USA'
when '1M2' then 'Mack Truck USA'
when '1M3' then 'Mack Truck USA'
when '1M4' then 'Mack Truck USA'
when '1N' then 'Nissan USA'
when '1NX' then 'NUMMI USA'
when '1P3' then 'Plymouth USA'
when '1R9' then 'Roadrunner Hay Squeeze USA'
when '1VW' then 'Volkswagen USA'
when '1XK' then 'Kenworth USA'
when '1XP' then 'Peterbilt USA'
when '1YV' then 'Mazda USA (AutoAlliance International) (Ford)'
when '2C3' then 'Chrysler Canada'
when '2D3' then 'Dodge Canada'
when '2FA' then 'Ford Motor Company Canada'
when '2FB' then 'Ford Motor Company Canada'
when '2FC' then 'Ford Motor Company Canada'
when '2FM' then 'Ford Motor Company Canada'
when '2FT' then 'Ford Motor Company Canada'
when '2FU' then 'Freightliner'
when '2FV' then 'Freightliner'
when '2FZ' then 'Sterling'
when '2G' then 'General Motors Canada'
when '2G1' then 'Chevrolet Canada'
when '2G2' then 'Pontiac Canada'
when '2G3' then 'Oldsmobile Canada'
when '2G4' then 'Buick Canada'
when '2HG' then 'Honda Canada'
when '2HK' then 'Honda Canada'
when '2HM' then 'Hyundai Canada'
when '2M' then 'Mercury'
when '2P3' then 'Plymouth Canada'
when '2T' then 'Toyota Canada'
when '2WK' then 'Western Star'
when '2WL' then 'Western Star'
when '2WM' then 'Western Star'
when '3D3' then 'Dodge Mexique'
when '3FE' then 'Ford Motor Company Mexique'
when '3G' then 'General Motors Mexique'
when '3H' then 'Honda Mexique'
when '3N' then 'Nissan Mexique'
when '3P3' then 'Plymouth Mexique'
when '3VW' then 'Volkswagen Mexique'
when '4F' then 'Mazda USA'
when '4M' then 'Mercury'
when '4S' then 'Subaru-Isuzu Automotive'
when '4T' then 'Toyota'
when '4US' then 'BMW USA'
when '4UZ' then 'Frt-Thomas Bus'
when '4V1' then 'Volvo'
when '4V2' then 'Volvo'
when '4V3' then 'Volvo'
when '4V4' then 'Volvo'
when '4V5' then 'Volvo'
when '4V6' then 'Volvo'
when '4VL' then 'Volvo'
when '4VM' then 'Volvo'
when '4VZ' then 'Volvo'
when '5F' then 'Honda USA-Alabama'
when '5L' then 'Lincoln'
when '5N1' then 'Nissan USA'
when '5NP' then 'Hyundai USA'
when '5T' then 'Toyota USA - camions'
when '6F' then 'Ford Motor Company Australie'
when '6G2' then 'Pontiac Australie (GTO)'
when '6H' then 'General Motors-Holden'
when '6MM' then 'Mitsubishi Motors Australie'
when '6T1' then 'Toyota Motor Corporation Australie'
when '8A1' then 'Renault Argentine'
when '8AG' then 'Chevrolet Argentine'
when '8GG' then 'Chevrolet Chili'
when '8AP' then 'Fiat Argentine'
when '8AF' then 'Ford Motor Company Argentine'
when '8AD' then 'Peugeot Argentine'
when '8GD' then 'Peugeot Chili'
when '8A1' then 'Renault Argentine'
when '8AK' then 'Suzuki Argentine'
when '8AJ' then 'Toyota Argentine'
when '8AW' then 'Volkswagen Argentine'
when '93U' then 'Audi Brésil'
when '9BG' then 'Chevrolet Brésil'
when '935' then 'Citroën Brésil'
when '9BD' then 'Fiat Automoveïs Brésil'
when '9BF' then 'Ford Motor Company Brésil'
when '93H' then 'Honda Brésil'
when '9BM' then 'Mercedes-Benz Brésil'
when '936' then 'Peugeot Brésil'
when '93Y' then 'Renault Brésil'
when '9BS' then 'Scania Brésil'
when '93R' then 'Toyota Brésil'
when '9BW' then 'Volkswagen Brésil'
when '9FB' then 'Renault Colombie'
else ''
end) as Marque
,loa.t_otbp as TiersVendeur
,loa.t_sfbp as TiersExpediteur
,tier.t_nama as NomTiersExpediteur
,loa.t_sfad as CodeAdresseExpediteur
,adte.t_nama as Adresse1
,adte.t_namc as Adresse2
,adte.t_ccty as Pays
,adte.t_pstc as CodePostal
,adte.t_cste as Departement
from ttdpur401500 loa
inner join ttccom100500 tier on tier.t_bpid = loa.t_sfbp --Tiers Expéditeur
inner join ttccom130500 adte on adte.t_cadr = loa.t_sfad --Adresse Tiers Expéditeur
inner join ttdpur400500 oa on oa.t_orno = loa.t_orno --Commandes Fournisseurs
inner join ttdpur402500 ligliee on ligliee.t_orno = loa.t_orno and ligliee.t_pono = loa.t_pono and ligliee.t_sqnb = loa.t_sqnb --Données de commandes liées
inner join ttssoc200500 os on os.t_orno = ligliee.t_srvo --On fait le lien avec l'os pour avoir ce qui touche à la réversibilité
inner join ttssoc210500 presta on presta.t_orno = ligliee.t_srvo --On fait le lien avec la ligne de prestation pour avoir le chassis
where left(loa.t_orno, 3) = 'LV7' --Les LV7 sont les OA de réversibilité, avec en plus le code article ci-dessous
and loa.t_item like '%REVERSIBILLOUEUR%' --On récupère la réversibilité avec cet article
and os.t_cwoc = 'LVS-RV'
and presta.t_crac = 'GA-RST'
and loa.t_odat between @date_f and @date_t --Bornage sur la date de commande
and oa.t_hdst != 30 --On ne prend pas les commandes fournisseurs annulées
order by adte.t_pstc